/* WARNING: This file was automatically generated by templito.
 * Do not manually edit this file if you plan to continue using templito.
 */
define(function () {
	var App = {};


	return App.PreTemplates;
});
